- lua/cokeline/buffers.lua
unique_prefix was broken on windows, this fixes it.
Also, should unique_prefix only be returned when the number of buffers > 1? 
Great plugin btw. :)
> :bug: fix: use correct path separators for unique_prefix depending on OS

- lua/cokeline/buffers.lua
`vim.fn.getbufinfo({ buflisted = 1 })` is not consistent on windows. Often it provides path with mixed path separators. Since we are just displaying the file name/path, it is better to convert windows path to linux path. 
Consequently, `local path_separator = (fn.has('win32') == 0) and '/' or '\\'` can be reverted to `local path_separator = '/'`.
Now, get_unique_prefix works as intended. I hope this doesn't break anything in linux 😅.
> :bug: fix: `unique_prefix` on windows

- README.md
usually people with nice configs for one plugin, have other cool things in their neovim setup, so i think it makes sense to drop these links in readme from beginning :)
> Add author links to readme

- lua/cokeline/mappings.lua
Fix a bug where if the current focused buffer is a non-valid one, you couldn't focus another buffer based on its index.
> fix: Allow focusing a buffer from a non-valid buffer

- lua/cokeline/mappings.lua
> fix: cokeline-pick-close and cokeline-pick-focus in v0.7

- lua/cokeline/buffers.lua
`not fn.has("win32") == 0` is always `false` even on Windows, as:
- `fn.has("win32")` returns `1` or `0`
- both `not 1` and `not 0` evaluate to `false` as [numbers always evaluate to true in lua](https://github.com/nanotee/nvim-lua-guide#caveats-4)
- `false == 0` is always `false`
Basically it would needs braces but it can also have this simple form: 
```lua
fn.has("win32") == 1
```
So it seems like its broken on Windows since 9fd956fc3f9550052acbc4451ec3e3020ffab983 (v0.1.0), possibly during refactor.
> fix: check for Windows always fails when computing `unique_prefix`

- README.md
- doc/cokeline.txt
- lua/cokeline/buffers.lua
Essentially the same concept as [PR 54](https://github.com/noib3/nvim-cokeline/pull/54), though I didn't include the later about exposing all buffers.
Adding the `is_first` and `is_last` buffer options allows configurations such as this
Where the first and last buffer have different left and right icons depending on if they are the first/last or not
> Adding is_last and is_first to buffer return

- README.md
- doc/cokeline.txt
- lua/cokeline/buffers.lua
- lua/cokeline/config.lua
This adds two config options: `pick.use_filename`, which lets you skip getting the pick letter from the filename, and `pick.letters`, which lets you change the order of letters used, for non-QWERTY layouts.
Closes #87.
> feat: `pick.use_filename` and `pick.letters` config options

- lua/cokeline/mappings.lua
When the picker mode is enabled (in focus or close mode), hitting `<C-c>` throw E5108: Error executing lua: Keyboard interrupt
This changes allow to handle `<C-c>` as if `<Esc>` was typed.
> fix(mapping): handle gracefully keyboard interrupt on buffer pick.

- README.md
- doc/cokeline.txt
- lua/cokeline/buffers.lua
Default neovim behavior for people who want to use their normal buffer switching binds
> feat: sorting by buffer number

- lua/cokeline/mappings.lua
- lua/cokeline/utils.lua
* fix: skip switching when closing non-open buffer
* feat: in mappings, `by_step` and `by_index` now support `'close'` as a goal
Closes #90
> feat: close by step and by index

- README.md
- lua/cokeline/buffers.lua
- lua/cokeline/components.lua
- lua/cokeline/config.lua
- lua/cokeline/context.lua
- lua/cokeline/handlers.lua
- lua/cokeline/init.lua
- lua/cokeline/rendering.lua
- lua/cokeline/sidebar.lua
- lua/cokeline/utils.lua
* Each component can now specify an optional `on_click` method
* Overhauled the event system to prepare for hover events and tab groups
> feat: per-component click handlers

- lua/cokeline/augroups.lua
- lua/cokeline/buffers.lua
When all available letters get assigned to buffers, a question mark (?)
starts to appear for each new one. The pick feature is then unusable
anymore for the upcoming buffers, even if we delete those with assigned
letters.
This PR simply release the assigned letter of a deleted buffer.
> feat(pick): release taken letters when deleting buffers

- README.md
- doc/cokeline.txt
- lua/cokeline/config.lua
- lua/cokeline/init.lua
- lua/cokeline/rendering.lua
Make the colors of the filler space configurable.
From `:h syntax.txt`, I think we should use `TabLineFill` instead of `TabLine`. This might break people's tabline color, so I make the highlight group a config option and naively pass it to the `render()` function.
```help
*hl-TabLine*
TabLine		Tab pages line, not active tab page label.
*hl-TabLineFill*
TabLineFill	Tab pages line, where there are no labels.
```
> feat: add fill_hl config option

- lua/cokeline/buffers.lua
Hey, thanks for such a cool plugin. In the past I struggled with tabline plugins and setting the paddings and names like I wanted, and this plugin just let us do everything we want it, I really appreciate it :pray: 
But I have found that the buffer_picker would not work very well when the filename starts with a mulibyte character, when we're using the filename to decide the picker character, or if we set multibyte characters in the `letters` option in the setup. And by multibyte character I mean things like `ç`, `ã`, `é` etc.
My keyboard layout has special characters, so I wanted to use them in the "letters" option, but then it would show some weird characters, like this:
Here my first letter should be `ç`, but it is shown as this weird `<c3>` thing on first buffer and `<a7>` on the …
> fix: allow multibyte characters on buffer picker

- README.md
- doc/cokeline.txt
- lua/cokeline/components.lua
- lua/cokeline/hlgroups.lua
Hello,
I added an option to pass highlight group names to components for better color scheme support. For example:
```lua
{
text = function(buffer)
return buffer.unique_prefix
end,
highlight = 'Comment'
},
```
Similarly to other options, `highlight` accepts both `string` with the highlight group name and `function(buffer) -> string`.
When `highlight` is passed, `fg`, `bg`, and `style` parameters are ignored.
> feat: support for passing highlight group names

- README.md
- doc/cokeline.txt
- lua/cokeline/augroups.lua
- lua/cokeline/buffers.lua
- lua/cokeline/config.lua
- lua/cokeline/history.lua
- lua/cokeline/init.lua
Adds a fixed-sized ringbuffer that keeps track of buffer history, and allows access to Buffer objects from anywhere. Size is configurable, and the history can be disabled if you don't want to use it.
Closes #109
> feat: buffer history ringbuffer

- lua/cokeline/hlgroups.lua
So it appears that the commit c29c2a1bd95c9145c403d81bef47667009d5041b makes the `Hlgroup.new` call get_hex on both fg and bg, but get_hex returns an empty string when we pass a name, like `red`. So we cannot set a component like this anymore:
```
{
text = ...,
fg = 'red',
}
```
Before it just simply passed the value as is to a `vim.cmd('highlight ...')`, so we could use color names without a problem.
I think it is nice to able to get the color of a hlgroup, which is what the mention commit does, so I think we should definitely keep that. I then started looking at the code and noticed that it looks at the first character passed to fg (or bg) and checks if it is a `#` to decide if the user passed a hlgroup name or a color.
After weird workarounds (that included hardcoding some names 😅 - …
> Use named color names

- README.md
- lua/cokeline/augroups.lua
- lua/cokeline/components.lua
- lua/cokeline/config.lua
- lua/cokeline/context.lua
- lua/cokeline/handlers.lua
- lua/cokeline/hover.lua
- lua/cokeline/init.lua
- lua/cokeline/rendering.lua
- lua/cokeline/rhs.lua
- lua/cokeline/sidebar.lua
- lua/cokeline/tabs.lua
Allows for tab components to be displayed in the tabline in addition to buffers. Tab components have the same API as buffer, sidebar and rhs components, except their methods take a TabPage object as context.
Closes #35
> feat: native tab support

- README.md
- lua/cokeline/buffers.lua
- lua/cokeline/components.lua
- lua/cokeline/hover.lua
- lua/cokeline/init.lua
- lua/cokeline/rendering.lua
- lua/cokeline/utils.lua
There's a lot of iteration involved in the rendering process, and a lot of it can be streamlined using iterators. This PR implements basic iterators and uses them where possible.
Ideally we would use vim.iter, but that would break compatibility with older neovim versions.
> perf: use stream-based iterators where possible

- README.md
- lua/cokeline/buffers.lua
- lua/cokeline/rendering.lua
- lua/cokeline/sidebar.lua
- lua/cokeline/tabs.lua
Component-local hover events are useful, but sometimes it's nice to have hover events for the entire buffer, tab, or section. This can be worked around by using closure-based components, but that's a bit of a dirty fix. This PR adds `tab_hovered` and `buf_hovered` properties so component nethods can check if *any* component in the section is currently hovered.
> feat: global (per buffer/tab/etc) hover events

- lua/cokeline/utils.lua
Previously, buffer would be listed and non-scratch. This doesn't make much sense as most users likely won't start editing an empty and unnamed file when deleting the last buffer.
> refactor!: make scratch buffer if deleting last buffer

- .github/workflows/lines.yaml
- lua/cokeline/buffers.lua
- lua/cokeline/config.lua
Closes #144 
Note that this is not a final solution and ultimately I'd like to refactor the way sorting is handled so that there are different levels of sort priority that can be determined by multiple providers. That way, you could quickly create different ordering providers and for example keep harpoon marks on the left, but still be able to sort the rest of your open buffers based on some other function.
However, this was super quick to implement so can't hurt to have for now :)
> feat: custom sorting functions

- lua/cokeline/components.lua
- lua/cokeline/hlgroups.lua
- lua/cokeline/utils.lua
Closes #147
This is a breaking change as the config for highlighting is slightly different. Instead of using a "style" property, individual properties such as `bold` or `underline` are set via `[name] = boolean`, or `[name] = fun(cx):boolean`, the same way that `fg`, `bg`, and `sp` are set.
> feat!: support for more highlight attrs

- README.md
commit: (3682c78e0b727c12fb84405b694c14cc1af4d64b) Removes support for
hl subtables and a single default hl table was used for buffers.
Reflect the changes inside the README configs as well.
Change-Id: I318d2c824fcd62606615910847abf1155e90440a
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>
> fixup: (3682c78e): README: Replace `focused` with `fg` in default_hl

- lua/cokeline/buffers.lua
Make `first_valid` a function-level variable rather than a module-level one.  This way when buffers are deleted, the letters at the begining of the list are re-used.
This improves the UX when `use_filename` is false:
- The letters at the begining of the list are likely to be the best ones.  My setup puts the home row keys at the start.
- Otherwise, if you keep deleting buffers you can use up all the letters and get `?` for all your buffers.
> Reuse pick letters

- lua/cokeline/tabs.lua
Fixes an issue where opening new tabs from a tab other than the last one causes a mismatch between the tab index and the ordering of tab components. This gets the index from neovim's api and is the same number used by `gt` and `gT` keymaps. Not sure if this breaks anything else though.
> use nvim's internal numbering for tab index

- lua/cokeline/components.lua
Hi
I'm not using components for buffers themselves (only for tabpages), so I set them as an empty table. But that caused crashes. So I added this one line to make sure it doesn't try to shorten components, if there are none
> Do not shorten components if there's nothing to shorten

- lua/cokeline/mappings.lua
Adds a mapping similar to `cokeline-pick-close` but stays in picking mode to allow closing multiple buffers without invoking the mapping again. Entering a character that isn't one of the buffer pick letters leaves the picking mode.
> Pick close multiple buffers
